### ISSUE TITLE
AutoRest shows almost no output after installing from npm

### ISSUE THREAD

**Issue by Inirit** [Azure/autorest#2749]
I'm having a problem using AutoRest installed from npm. Using the latest version (2.0.4215), the only console output I ever seem to get is the banner text. Downgrading to a previous version (2.0.4143) I now see console output.

Here's a segmented image to show what I'm talking about:
![image](https://user-images.githubusercontent.com/15949541/33508791-813bdd44-d6b1-11e7-84ef-225a2511541c.png)

#2686 Seems to be describing a similar (or the same) issue, but the issue was closed with the solution of reformatting. Reformatting isn't a feasible option for me and that's not really a solution anyway.

I'm using npm 5.5.1 with node 9.2.0, running on Windows 7 64-bit

**Comment by fearthecowboy** [comment]
try `autorest --reset ` after updating.

That may be necessary to remove older plugins. They shouldn't be holding you back, but that might be. If it is, I should look into that.

the other thing to try is running with `--verbose --debug` and see if it says anything else.

**Comment by Inirit** [comment]
I've given those things a try, I got some output but it doesn't appear to be in a working state.

![image](https://user-images.githubusercontent.com/15949541/33509052-54c625d8-d6b3-11e7-89e8-26a2dd87897d.png)

**Comment by Inirit** [comment]
I'm thinking there's something messed up with my node/npm install. I used the installer available from their website, but perhaps it was a mistake to use current rather than LTS. I'm going to clean up my node install and try again.

**Comment by fearthecowboy** [comment]
I just installed node 9.2.0 w/npm 5.5.1 and I don't see this.

We're a bit stumped; maybe try another build/version..

8.9.0 is very good for me :D

**Comment by Inirit** [comment]
I'm currently installing node 8.9.1, but in the meantime there is one bit info that I left out. I'm currently on a corporate network that interferes with SSL. I have to configure some additional certs on npm so that npm install actually works. Would that be relevant to AutoRest in some way?

**Comment by fearthecowboy** [comment]
Oh, that certainly might be. We use npm (and yarn) internally to pull down plugins, and I haven't played with the proxy settings.

I'm prepping an all-in-one zip file right now, give me a few minutes, and I might have a different solution for you.

**Comment by Inirit** [comment]
I think it might be fixed? This is the result of my latest attempt using node 8.9.1

![image](https://user-images.githubusercontent.com/15949541/33509404-262c474a-d6b6-11e7-816e-f5bb0b9e6081.png)

Initially I was getting no output like before, but then I ran autorest --reset and that actually seemed to fix it. I haven't tried codegening anything yet, but this is further than I was before.

**Comment by fearthecowboy** [comment]
that looks better !

try adding `--csharp --verbose --debug --help` and you should see it install the extension. if it gets that far, we're golden.

**Comment by Inirit** [comment]
Done, I see a "C# Generator" help section which wasn't there before which I assume means it worked.

**Comment by fearthecowboy** [comment]
yay! That means it's there!

**Comment by Inirit** [comment]
And now I've verified that I can codegen things. I don't know if it looks how I want, but any problems there would be a different issue.

Tangentially, I mistakenly opened the wrong swagger file and came across a typo in an error string :)
![image](https://user-images.githubusercontent.com/15949541/33509573-a1646de2-d6b7-11e7-8d4e-35ebba2f312d.png)

**Comment by olydis** [comment]
whooops, typo fixed in next version

**Comment by MartinF** [comment]
Just want to add that I had the exact same problem with the same installation (which led me here).
Tried to do a autorest --reset, but it made no difference. Then uninstalled 9.2 and installed 8.9.2 instead - still the same problem, then tried to do a autorest --reset again and this time information was printed in the console and I was afterwards able to run the generator.

**Comment by fearthecowboy** [comment]
*sigh*

The unstable node yet again foils things. 8.x was kinda flakey right up until 8.9.

The worst part is there isn't a way to predict it, and I was unable to reproduce the problem locally.

**Comment by wdspider** [comment]
I am having the same problem where autorest is not outputting anything; therefore, I attempted to perform the reset as mentioned in this thread.  Unfortunately, I currently receive the following error message when attempting `autorest --reset`
![autorest](https://user-images.githubusercontent.com/5971649/34579735-22ad94d6-f13f-11e7-9cc9-253effda9512.png)

**Comment by fearthecowboy** [comment]
That's an error in the native zlib code in node. Perhaps node 9.x is not ready for primetime yet; Try switching to 8.9.1

**Comment by wdspider** [comment]
hmmmz.... I've been using node 9.x since Nov 2017 issue free with my Angular dev work.  I only ran into the issue today after attempting to check this package out.

**Comment by fearthecowboy** [comment]
Not every use flexes every feature in node. We found 8.x had some serious issues right up until about 8.9.  I know others have had issues with 9.2.0 

I just tried node 9.3.0 and it tells me exactly what's wrong: 

![image](https://user-images.githubusercontent.com/133736/34580509-280cdc72-f142-11e7-99bf-11cb80dbb6a8.png)

Node 9.x seems to have changed something internally and is incompatible with older versions of `npm` and `node-tar` (which is used in the package installer we have in AutoRest).

This kinda sucks; I'm going to have to update the npm dependency to work with the node 9.x. 

Sorry, until I get that rebuilt and tested, you're going to have to use node 8.9.x 😞

**Comment by fearthecowboy** [comment]
FYI I'm testing the fix for node 9.x right now; as long as it passes CI, we should be good to go.

**Comment by ktersius** [comment]
Also unable to use autorest. Tried different versions but it just shows the same output.

```
λ autorest --help
AutoRest code generation utility [version: 2.0.4238; node: v8.9.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
```

**Comment by MiYanni** [comment]
It sounds like this issue was resolved. Closing.
