### ISSUE TITLE
#3926 regression: Self-signed certificates

### ISSUE THREAD

**Issue by cpboyd** [Azure/autorest#3944]
**Describe the bug**
See previously documented bug: #3341
For those of us behind a corporate proxy with self-signed certificates, we need a way to configure that.
With the built-in `yarn`, there's no clear way to do that.

Reverting to v3.1.1 works.

**Expected behavior**
autorest should function behind a proxy.

**Additional context**
#3341
Breaking change: #3926

**Comment by timotheeguerin** [comment]
Hi @cpboyd how were you configuring the proxy settings before?

Does settings the `http_proxy` and/or `https_proxy` environment variables not working?

**Comment by cpboyd** [comment]
@timotheeguerin I'm specifying either `yarn config set strict-ssl false` or `yarn config set cafile <certificate>`.
Is there a workaround to specify the appropriate yarn config?

As an aside, why is it using `yarn` internally instead of just reusing the global `npm` (since that's one of the requirements according to the install doc)?

**Comment by timotheeguerin** [comment]
@cpboyd for the certificate issue you should be able to set `NODE_TLS_REJECT_UNAUTHORIZED=0` or `NODE_EXTRA_CA_CERTS`

For the reason of using built in yarn vs system npm, I am not exactly sure what was the reasoning when this was added but guessing this is to not be affected by any system specific issues around this(Example being the problem that was fixed that introduced your issue)

**Comment by cpboyd** [comment]
@timotheeguerin I tried `NODE_TLS_REJECT_UNAUTHORIZED=0`, but that doesn't seem to impact yarn. Same errors persist.

**Comment by cpboyd** [comment]
> We could look into adding those to be autorest configuration so they are set automatically or can be passed as CLI flags.

If keeping the internal yarn is necessary, then ideally there should be a way to pass yarn configuration down or otherwise specify a local `.yarnrc` config.

**Comment by timotheeguerin** [comment]
hhm, yeah looking at some yarn issues seems like having `strict-ssl` in a yarn config is the only way. Now yarn is not the only part of autorest doing remote calls. Are you never using autorest with remote specs? Would preferably want to find a solution that works for both scenarios and not have to specify a yarnrc config as well as an autorest specific config

**Comment by cpboyd** [comment]
For my present use-case, I'm using a localhost dev API that is ultimately being published to Azure.
I'm not following how remote/local impacts yarn's ability to install the package, though.

**Comment by timotheeguerin** [comment]
Alternativel would be to remove the `--no-default-rc` to still use the global yarn config but use `YARN_IGNORE_PATH=1` instead to prevent a different version of yarn from being loaded(Issue solved in #3926)

**Comment by timotheeguerin** [comment]
@cpboyd could you confirm that using `--version:https://tinyurl.com/y7fp38fb` resolve the issue for you?

**Comment by cpboyd** [comment]
@timotheeguerin Yes, that works.

**Comment by drmcclelland** [comment]
The suggestion in #3341 to install yarn separately worked for me, then I was able to issue the command `yarn config set strict-ssl false -g` to fix this error message:

```
AutoRest code generation utility [cli version: 3.2.0; node: v12.18.3, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Yarn log:
--------------------------------------------------
{"type":"info","data":"No lockfile found."}
{"type":"step","data":{"message":"Resolving packages","current":1,"total":4}}
{"type":"error","data":"An unexpected error occurred: \"https://registry.npmjs.org/@autorest/csharp/-/csharp-3.0.0-beta.20210428.6.tgz: unable to get local issuer certificate\"."}
{"type":"info","data":"If you think this is a bug, please open a bug report with the information provided in \"C:\\\\Users\\\\dmcclelland1\\\\.autorest\\\\@autorest_csharp@3.0.0-beta.20210428.6\\\\yarn-error.log\"."}
{"type":"info","data":"Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command."}

--------------------------------------------------
Failure:
Error: Package '@autorest/csharp' - '3.0.0-beta.20210428.6' failed to install:
  Failed to install package 'https://registry.npmjs.org/@autorest/csharp/-/csharp-3.0.0-beta.20210428.6.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@autorest/csharp/-/csharp-3.0.0-beta.20210428.6.tgz' -- Error: Process Failed.
```
